
conquer_traits = {
    ["FactionConqueror"] = 1,
    ["VictorVirtue"] = 1,
    ["MinasIthilLiberator"] = 0,
    ["MinasIthilConqueror"] = 0,
    ["MinasTirithConqueror"] = 0,
    ["MinasTirithSacker"] = 0,
    ["PelargirConqueror"] = 0,
    ["PelargirSacker"] = 0,
    ["DolAmrothConqueror"] = 0,
    ["DolAmrothSacker"] = 0,
    ["EdorasConqueror"] = 0,
    ["EdorasPillager"] = 0,
    ["HornburgConqueror"] = 0,
    ["FennasDruinConqueror"] = 0,
    ["FennasDruinPillager"] = 0,
    ["FornostErainConqueror"] = 0,
    ["BreeConqueror"] = 0,
    ["BreePillager"] = 0,
    ["BeornsHallsConqueror"] = 0,
    ["BeornsHallsPillager"] = 0,
    ["DaleConqueror"] = 0,
    ["DalePlunderer"] = 0,
    ["EsgarothConqueror"] = 0,
    ["EsgarothPillager"] = 0,
    ["CarasSantConqueror"] = 0,
    ["CarasSantSacker"] = 0,
    ["UmbarConqueror"] = 0,
    ["UmbarSacker"] = 0,
    ["FaenobelConqueror"] = 0,
    ["FaenobelSacker"] = 0,
    ["KhandConqueror"] = 0,
    ["KhandSacker"] = 0,
    ["MistrandConqueror"] = 0,
    ["MistrandSacker"] = 0,
    ["MithlondConqueror"] = 0,
    ["MithlondDespoiler"] = 0,
    ["ImladrisConqueror"] = 0,
    ["ImladrisDespoiler"] = 0,
    ["CarasGaladhonConqueror"] = 0,
    ["CarasGaladhonDespoiler"] = 0,
    ["ThranduilsHallsConqueror"] = 0,
    ["ThranduilsHallsDespoiler"] = 0,
    ["EreborConqueror"] = 0,
    ["EreborPlunderer"] = 0,
    ["ThorinsHallsConqueror"] = 0,
    ["ThorinsHallsPlunderer"] = 0,
    ["CarnDumConqueror"] = 0,
    ["GundabadLiberator"] = 0,
    ["GundabadConqueror"] = 0,
    ["DainsHallsLiberator"] = 0,
    ["DainsHallsConqueror"] = 0,
    ["WestMoriaLiberator"] = 0,
    ["WestMoriaConqueror"] = 0,
    ["EastMoriaLiberator"] = 0,
    ["EastMoriaConqueror"] = 0,
    ["GoblintownConqueror"] = 0,
    ["DolGuldurConqueror"] = 0,
    ["AmonLancLiberator"] = 0,
    ["IsengardConqueror"] = 0,
    ["KirikhgatholConqueror"] = 0,
    ["KirikhgatholPlunderer"] = 0,
    ["DunLarachConqueror"] = 0,
    ["DunLarachPillager"] = 0,
    ["AlcfudConqueror"] = 0,
    ["AlcfudPillager"] = 0,
    ["MorannonConqueror"] = 0,
    ["BaradDurConqueror"] = 0,
    ["BattleChivalryGood"] = 7,
    ["BattleChivalryEvil"] = 7,
  }
  
  conquer_traits_units = {
    ["special"] = {
        "Pale Uruks",
        "Dunedain Steelbowmen",
        "Citadel Guard",
        "Temple Knights",
        "Hearthguard",
        "Elvellyn Hammerguard",
        "Framsguard",
        "Witch-Realm Inquisitors",
        "Enedwaith Marksmen",
        "Troll-men Champions",
        "Warlords Kataphracts",
        "Dragons Wrath Guardians",
        "Mithril Bodyguard",
        "Gabilgathol Guard",
        "Axeguard of Erebor",
        "Aredhirith",
        "Berio I Ngelaidh",
        "Elderinwe Roquen",
        "Saurons Will",
        "Castellans of Dol Guldur",
        "Black Pit Berserkers",
        "Guard of the Hand",
    },
  }

original_general_units_list = {}

mod_general_units_list = {
    {name="Rohan Bodyguard",size=21,faction="milan",},
    {name="Pharazim Nobles",size=21,faction="russia",},
    {name="Dunedain Bodyguard",size=40,faction="turks",},
    {name="Gondor Bodyguard",size=45,faction="sicily",},
    {name="Royal Guardsmen",size=40,faction="scotland",},
    {name="High Paladins",size=45,faction="byzantium",},
    {name="Skin-Changers",size=45,faction="timurids",},
    {name="Angmar Bodyguards",size=45,faction="portugal",},
    {name="Brenin's Guard",size=45,faction="aztecs",},
    {name="Black Snake Guard",size=21,faction="spain",},
    {name="Variag Nobles",size=21,faction="venice",},
    {name="Loke Rim Bodyguard",size=50,faction="khand",},
    {name="Zenith Guard",size=45,faction="norwat",},
    {name="Tumunzahar Nobles",size=40,faction="hungary",},
    {name="Durins Guard",size=45,faction="moors",},
    {name="Tawar Areiniyr",size=35,faction="mongols",},
    {name="Elbereths Sentinels",size=35,faction="ireland",},
    {name="Calaquendi Lords",size=28,faction="denmark",},
    {name="Uruk Bodyguard",size=58,faction="england",},
    {name="Mirkwood Bodyguard",size=45,faction="poland",},
    {name="Goblin Bodyguards",size=58,faction="hre",},
    {name="Blue Crag Bodyguards",size=58,faction="normans",},
    {name="Mountain Guard",size=45,faction="gundabad",},
    {name="Uruk-hai Bodyguards",size=45,faction="france",},
    {name="Noldorin Bodyguards",size=49,faction="saxons",},
    {name="Realm Sentinels",size=35,faction="egypt",},
}

default_general_units = {
    ["milan"] = {
        old = "Rohan Bodyguard",
        new = "Rohirrim",
    },
    ["normans"] = {
        old = "Blue Crag Bodyguards",
        new = "Blue Crag Orc Blunt",
    },
    ["sicily"] = {
        old = "Gondor Bodyguard",
        new = "Territorial Guardsmen",
    },
    ["turks"] = {
        old = "Dunedain Bodyguard",
        new = "Dunedain Rangers",
    },
    ["russia"] = {
        old = "Pharazim Nobles",
        new = "Belegaer Footmen",
    },
    ["scotland"] = {
        old = "Royal Guardsmen",
        new = "Dalian Swordsmen",
    },
    ["byzantium"] = {
        old = "High Paladins",
        new = "Thorn Bladesmen",
    },
    ["timurids"] = {
        old = "Skin-Changers",
        new = "Vale Archers",
    },
    ["portugal"] = {
        old = "Angmar Bodyguards",
        new = "Angmarim Infantry",
    },
    ["aztecs"] = {
        old = "Brenin's Guard",
        new = "Clan Spearmen",
    },
    ["teutonic_order"] = {
        old = "Clan Heralds",
        new = "Keefei Huntsmen",
    },
    ["spain"] = {
        old = "Black Snake Guard",
        new = "Southron Warband",
    },
    ["khand"] = {
        old = "Variag Nobles",
        new = "Nomad Horsemen",
    },
    ["venice"] = {
        old = "Loke Rim Bodyguard",
        new = "Claw-Guard",
    },
    ["norway"] = {
        old = "Zenith Guard",
        new = "Khazad Sentries",
    },
    ["hungary"] = {
        old = "Tumunzahar Nobles",
        new = "Ered Luin Militia",
    },
    ["moors"] = {
        old = "Durins Guard",
        new = "Erebor Infantry",
    },
    ["mongols"] = {
        old = "Tawar Areiniyr",
        new = "Woodland Spearmen",
    },
    ["ireland"] = {
        old = "Elbereths Sentinels",
        new = "Lorien Warders",
    },
    ["denmark"] = {
        old = "Calaquendi Lords",
        new = "Lindar Guards",
    },
    ["england"] = {
        old = "Uruk Bodyguard",
        new = "Orc Raiders",
    },
    ["poland"] = {
        old = "Mirkwood Bodyguard",
        new = "Dol Guldur Archers",
    },
    ["hre"] = {
        old = "Goblin Bodyguards",
        new = "Goblin Band",
    },
    ["gundabad"] = {
        old = "Mountain Guard",
        new = "Snow-Orc Raiders",
    },
    ["france"] = {
        old = "Uruk-hai Bodyguards",
        new = "Uruk-hai Raiders",
    },
    ["saxons"] = {
        old = "Noldorin Bodyguards",
        new = "Spear Quendi",
    },
    ["egypt"] = {
        old = "Realm Sentinels",
        new = "Gathring Shieldbearers",
    },
}

labtrait_units_list = {
    ["Denethor"] = "Stewards Guards",
    ["Boromir"] = "Boromir's Company",
    ["Angbor"] = "Lamedon Clansmen",
    ["Faramir"] = "Captain's Rangers",
    ["Hirluin"] = "Pinnath Gelin Cavalry",
    ["Orodreth"] = "Lebennin Marines",
    ["Adrahil"] = "Tirith Aear Wardens",
    ["Imrahil"] = "Royal Swan-Guard",
    ["Cirdan"] = "Falas Lords",
    ["Theoden"] = "King's Horseguard",
    ["Theodred_eop_1"] = "King's Horseguard",
    ["Eomund_eop_1"] = "Riders of the Fold",
    ["Eomer_eop_1"] = "The Red Shields of Erkenbrand",
    ["Erkenbrand_eop_1"] = "The Red Shields of Erkenbrand",
    ["Gamling_eop_1"] = "Red Axemen of Westfold",
    ["Hama"] = "Golden Hall Spearmen",
    ["Aragorn"] = "Grey Company",
    ["Halbarad"] = "Dunedain Steelbowmen",
    ["Brand_eop_1"] = "Hearthguard",
    ["Vidusith_eop_1"] = "Lake-town Pikemen",
    ["Beorn_eop_1"] = "Beorning Shapeshifters",
    ["radagast"] = "Ents",
    ["Fastred_eop_1"] = "Silvan Marchwardens",
    ["Folcred"] = "Woodman Wardens",
    ["Gleowine"] = "Eotheod Archers",
    ["Forthwin"] = "Regent Axeguard",
    ["Athalhere_eop_1"] = "Athala Rangers",
    ["Nurwe"] = "Moriquendi Sentinels",
    ["Dain"] = "King's Mounted Hammerguard",
    ["Gimli"] = "Axeguard of Erebor",
    ["Gor_eop_1"] = "Gabilgathol Guard",
    ["Grain_eop_1"] = "Broadbeam Marksmen",
    ["Balin"] = "Balins Guard",
    ["Maernil"] = "Storm Guard",
    ["Elrond"] = "GilGalads Company",
    ["Elladan"] = "Dunedain Bodyguard Twins",
    ["Elrohir"] = "Dunedain Troll Slayers",
    ["Gildor"] = "Noldorin Archers",
    ["Celeborn"] = "Berio I Ngelaidh",
    ["Haldir"] = "Galadhrim Archers",
    ["Thranduil"] = "Aredhirith",
    ["Legolas"] = "Hin e-Daur",
    ["Tremac"] = "Mochaini Ambaxtoi",
    ["Donnchaidh_eop_1"] = "Dubhshith Foresters",
    ["Margoz"] = "Loke-Nar Rim",
    ["Sauron"] = "Sauron",
    ["goblinking_1"] = "Goblin King",
    ["Gothmog"] = "Morgul Chosen",
    ["Ulairon"] = "Khamuls Shadow Rangers",
    ["Saruman"] = "Guard of the Hand",
    ["Yagthak"] = "Orthanc Guard",
    ["Freca_eop_1"] = "Frekkalingir Harriers",
    ["Menthar_eop_1"] = "Dunhird Slayers",
    ["Uglag_eop_1"] = "Mountain Uruks",
    ["Agorolg_eop_1"] = "Warg Riders",
    ["Lunug_eop_1"] = "Black Pit Berserkers",
    ["Mazog"] = "Pale Uruks",
    ["Ghurzog_eop_1"] = "Orc Avengers",
    ["Hazolg_eop_1"] = "Orc Avengers",
    ["agandaur_1"] = "Northguard",
    ["Hunvorn"] = "Rebel Barrow Wights",
    ["Scyld_eop_1"] = "Darkblades",
    ["Morholt"] = "Rhudaur Huscarles",
    ["Drangu"] = "Mount Gram Raiders",
    ["Utbah_eop_1"] = "Serpent Bladesmen",
    ["Gimilkhad"] = "Royal Legion of Armenelos",
    ["bn_army_2"] = "Naru n'Aru Sentinels",
    ["bn_army_3"] = "Darkblades",
    ["gondor_attackers_m"] = "Osgiliath Veterans",
    ["lurtz_1"] = "Lurtz's Hunting Pack",
    ["Ugluk"] = "Berserkers",
    ["Luag"] = "Brenin's Guard",
    ["gandalf_3"] = "Arthedain Royal Guard",
    ["Bane"] = "Moria Balrog",
    ["Taraghlan_eop_1"] = "Wulfguard Axemen",
    ["Glirhuin_eop_1"] = "Wulfguard Pikes",
    ["Erunestian_eop_1"] = "Liadan Spearmen",
    ["Melmidoc_eop_1"] = "Faolan Warriors",
    ["Fionghan_eop_1"] = "Mordag Skirmishers",
    ["Ghan_eop_1"] = "Druedain Hunters",
    ["Coruion_eop_1"] = "Fylani War Wagons",
    ["Seitheach_eop_1"] = "Tir Croicoill Cosantoiri",
    ["glorfindel_1"] = "Eldarinwe Bodyguards",
    ["dornornoston_1"] = "Eregion Smiths",
    ["rumil_1"] = "Lothlorien Marchwardens",
    ["orophin_1"] = "Lothlorien Marchwardens",
    ["enpremi_1"] = "Galadhrim Swordsmen",
    ["orthordir_1"] = "Elvenkings Gateguard",
    ["faramir_rk"] = "Captain's Rangers",
    ["boromir_rk"] = "Boromir's Company",
    ["hurin_rk"] = "Raven Helms of Cair Andros",
    ["angbor_rk"] = "Lamedon Clansmen",
    ["denethor_rk"] = "Stewards Guards",
    ["mistven_rk"] = "Tirith Aear Wardens",
    ["adrahil_rk"] = "Tirith Aear Wardens",
    ["imrahil_rk"] = "Royal Swan-Guard",
    ["istion_rk"] = "Royal Swan-Guard",
    ["Dinenion_eop_1"] = "Gondor Infantry",
    ["duinhir_rk"] = "Blackroot Vale Archers",
    ["forlong_rk"] = "Lossarnach Axemen",
    ["Forlong"] = "Lossarnach Axemen",
    ["golasgil_rk"] = "Gondor Pikemen",
    ["Iorthon_eop_1"] = "Royal Swan-Guard",
    ["Baragund_eop_1"] = "Lebennin Marines",
    ["orodreth_rk"] = "Lebennin Marines",
    ["Kavatha_eop_1"] = "Dragon-Wrath Swiftblades",
    ["Rudaz_eop_1"] = "Dragon-Wrath Shields",
    ["Jasur_eop_1"] = "Suriut Chariots",
    ["Ubaadah_eop_1"] = "Troll-men Champions",
    ["Khaldoon_eop_1"] = "Hasharii Blades",
    ["Umaarah_eop_1"] = "Troll-men Warriors",
    ["ancantar_3"] = "Temple Knights",
    ["alatar_1"] = "Iron Fist Hammers",
    ["pallando_1"] = "Blacklock Engineers",
    ["ancantar_1"] = "Temple Knights",
    ["thranduil_union"] = "Aredhirith",
    ["legolas_union"] = "Hin e-Daur",
    ["orthordir_union"] = "Elvenkings Gateguard",
    ["enpremi_union"] = "Galadhrim Swordsmen",
    ["rumil_union"] = "Lothlorien Marchwardens",
    ["orophin_union"] = "Lothlorien Marchwardens",
    ["celeborn_union"] = "Berio I Ngelaidh",
    ["haldir_union"] = "Galadhrim Archers",
    ["gandalf_2"] = "Arthedain Royal Guard",
    ["gandalf_1"] = "Cardolan Riders",
    ["guardian_moria_1"] = "Goblin Bodyguards",
    ["oin_1"] = "Khazad-dum Reclaimers",
    ["balrog_1"] = "Balrog",
    ["Ja_Sur_eop_1"] = "Loke Rim Bodyguard",
    ["Gazluk_eop_1"] = "Temple Wards",
}

bgunlock_units_list = {
}

not_increase_guard = {
    "sauron_1",
    "balrog_1",
    "balrog_2",
    "balrog_3",
    "radagast",
    "goblinking_1",
}