UNIT_UPGRADES_default_fr = {

    -- moors
    ["Erebor Axethrowers"] = { unit = { "Erebor Infantry", "Kings Warriors" }, expRequirement = { 2, 5 }, cost_multi = { 0.5, 1 }, counter = { "", "" } },
    ["Erebor Infantry"] = { unit = { "Erebor Axethrowers", "Kings Shields" }, expRequirement = { 2, 5 }, cost_multi = { 0.5, 1 }, counter = { "", "" } },
    ["Iron Guard"] = { unit = { "Legionaries of Erebor" }, expRequirement = { 9 }, cost_multi = { 2 }, counter = { "" } },
    ["Iron Hills Mattocks"] = { unit = { "Kings Axes" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Kings Shields"] = { unit = { "Iron Guard" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Kings Warriors"] = { unit = { "Axeguard of Erebor" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    ["Stonefoot Spearmen"] = { unit = { "Stiffbeard Archers" }, expRequirement = { 2 }, cost_multi = { 0.5 }, counter = { "" } },
    ["Stiffbeard Archers"] = { unit = { "Stonefoot Spearmen" }, expRequirement = { 2 }, cost_multi = { 0.5 }, counter = { "" } },
    
    -- norway
    ["Dwarven Labourers"] = { unit = { "Erebor Infantry", "Ered Luin Militia", "Khazad Volunteers" }, expRequirement = { 2, 2, 2 }, cost_multi = { 1, 1, 1 }, counter = { "", "", ""  }, faction = { "moors", "hungary", "norway" } },
    ["Khazad Sentries"] = { unit = { "Dwarven Travellers","Khazad Volunteers", "Legion Shieldguard" }, expRequirement = { 2,2, 5 }, cost_multi = { 0.5,0.5, 1 }, counter = { "", "","" } },
    ["Khazad Volunteers"] = { unit = { "Dwarven Travellers","Khazad Sentries", "Legion Deeping Guard" }, expRequirement = { 2,2, 5 }, cost_multi = { 0.5,0.5, 1 }, counter = { "", "","" } },
    ["Dwarven Travellers"] = { unit = { "Khazad Volunteers","Khazad Sentries", "Hithaeglir Beast Hunters" }, expRequirement = { 2,2, 5 }, cost_multi = { 0.5,0.5, 1 }, counter = { "norway", "norway","norway" } },
    --["Legion Crossbows"] = { unit = { "Blacklock Engineers" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Legion Deeping Guard"] = { unit = { "Khazad-dum Guardians" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Legion Shieldguard"] = { unit = { "First Legion" }, expRequirement = { 9 }, cost_multi = { 2 }, counter = { "" } },
    ["Legion Hammerguard"] = { unit = { "Khazad-dum Reclaimers" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Hithaeglir Beast Hunters"] = { unit = { "Legion Crossbows" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "norway" } },
    
    -- hungary
    ["Ered Luin Militia"] = { unit = { "Ered Luin Scouts", "Ered Luin Militia Spearmen", "Ered Luin Militia Pikemen", "Longbeard Javelins" }, expRequirement = { 2,2, 2, 5 }, cost_multi = { 0.5,0.5, 0.5, 1 }, counter = { "","", "", "" } },
    ["Ered Luin Militia Spearmen"] = { unit = { "Ered Luin Scouts", "Ered Luin Militia", "Ered Luin Militia Pikemen", "Longbeard Spearmen" }, expRequirement = { 2,2, 2, 5 }, cost_multi = { 0.5,0.5, 0.5, 1 }, counter = { "","", "", "" } },
    ["Ered Luin Militia Pikemen"] = { unit = { "Ered Luin Scouts", "Ered Luin Militia", "Ered Luin Militia Spearmen", "Longbeard Spearmen" }, expRequirement = { 2,2, 2, 5 }, cost_multi = { 0.5,0.5, 0.5, 1 }, counter = { "","", "", "" } },
    ["Ered Luin Scouts"] = { unit = { "Ered Luin Militia", "Ered Luin Militia Spearmen", "Ered Luin Militia Pikemen","Longbeard Crossbows" }, expRequirement = { 2,2, 2, 5 }, cost_multi = { 0.5,0.5, 0.5, 1 }, counter = { "","", "", "" } },
    ["Longbeard Javelins"] = { unit = { "Gabilgathol Barukram" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Longbeard Spearmen"] = { unit = { "Gabilgathol Pikemen" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    --["Firebeard Warriors"] = { unit = { "Gabilgathol Guard" }, expRequirement = { 9 }, cost_multi = { 2 }, counter = { "" } },
    
    
    -- milan
    --["Eored Axemen"] = { unit = { "Eored Footmen", "Eored Swordsmen" }, expRequirement = { 5, 5 }, cost_multi = { 0.5, 0.5 }, counter = { "", "" } },
    ["Peasant Militia"] = { unit = {"Eorling Spearmen" }, expRequirement = { 3 }, cost_multi = {  1 }, counter = {  "" } },
    ["Eored Footmen"] = { unit = {"Golden Hall Spearmen" }, expRequirement = { 5 }, cost_multi = {  1 }, counter = {  "" } },
    ["Eored Swordsmen"] = { unit = { "Golden Hall Swordsmen" }, expRequirement = {  5 }, cost_multi = { 1 }, counter = { "" } },
    ["Eorling Archers"] = { unit = { "Eorling Spearmen", "Helmingas" }, expRequirement = { 2, 5 }, cost_multi = { 0.5, 1 }, counter = { "", "" } },
    ["Eorling Spearmen"] = { unit = { "Eorling Archers", "Eored Footmen" }, expRequirement = { 2, 5 }, cost_multi = { 0.5, 1 }, counter = { "", "" } },
    ["Rohirrim"] = { unit = { "Rohirrim Archers", "Riddermark Cavalry", "Eored Lancers" }, expRequirement = { 2, 5, 5 }, cost_multi = { 0.5, 1, 1 }, counter = { "", "", "" } },
    ["Rohirrim Archers"] = { unit = { "Rohirrim", "Eored Skirmishers", "Riders of the Fold" }, expRequirement = { 2, 5, 5 }, cost_multi = { 0.5, 1, 1 }, counter = { "", "", "" } },
    
    -- sicily
    ["Territorial Swordsmen"] = { unit = { "Territorial Guardsmen", "Territorial Watchmen", "Gondor Infantry" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Territorial Guardsmen"] = { unit = { "Territorial Swordsmen", "Territorial Watchmen", "Gondor Spearmen" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Territorial Watchmen"] = { unit = { "Territorial Swordsmen", "Territorial Guardsmen", "Gondor Archers" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Lamedon Clansmen"] = { unit = { "Lamedon Champions" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Lebennin Marines"] = { unit = { "Gondor Infantry" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Anfalas Herdsmen"] = { unit = { "Gondor Archers" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Blackroot Vale Archers"] = { unit = { "Gondor Archers" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Lossarnach Axemen"] = { unit = { "Lossarnach Household Guard2" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Ringlo Pikemen"] = { unit = { "Ringlo House Guards2" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Territorial Cavalry"] = { unit = { "Gondor Cavalry" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Pinnath Gelin Cavalry"] = { unit = { "Riders of the Green Hills" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Gondor Spearmen"] = { unit = { "Citadel Guard" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Gondor Infantry"] = { unit = { "Anorien Defenders" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Gondor Archers"] = { unit = { "Anorien Wardens" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    
    -- normans
    ["Blue Crag Blunt"] = { unit = { "Blue Crag Dual", "Blue Crag Skirmishers", "Blue Crag Slingers", "Teraig Halberds" }, expRequirement = { 2, 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5, 1 }, counter = { "", "", "", "" } },
    ["Blue Crag Dual"] = { unit = { "Blue Crag Blunt", "Blue Crag Skirmishers", "Blue Crag Slingers", "Blue Crag Warg Warriors" }, expRequirement = { 2, 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5, 1 }, counter = { "", "", "", "" } },
    ["Blue Crag Skirmishers"] = { unit = { "Blue Crag Blunt", "Blue Crag Dual", "Blue Crag Slingers", "Teraig Infantry" }, expRequirement = { 2, 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5, 1 }, counter = { "", "", "", "" } },
    ["Blue Crag Slingers"] = { unit = { "Blue Crag Blunt", "Blue Crag Dual", "Blue Crag Skirmishers", "Teraig Slingers" }, expRequirement = { 2, 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5, 1 }, counter = { "", "", "", "" } },
    ["Blue Crag Goblin Axes"] = { unit = { "Blue Crag Goblin Dual", "Blue Crag Goblin Spears", "Blue Crag Goblin Slingers", "Teraig Halberds" }, expRequirement = { 2, 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5, 1 }, counter = { "", "", "", "" } },
    ["Blue Crag Goblin Dual"] = { unit = { "Blue Crag Goblin Axes", "Blue Crag Goblin Spears", "Blue Crag Goblin Slingers", "Blue Crag Warg Warriors" }, expRequirement = { 2, 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5, 1 }, counter = { "", "", "", "" } },
    ["Blue Crag Goblin Spears"] = { unit = { "Blue Crag Goblin Axes", "Blue Crag Goblin Dual", "Blue Crag Goblin Slingers", "Teraig Infantry" }, expRequirement = { 2, 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5, 1 }, counter = { "", "", "", "" } },
    ["Blue Crag Goblin Slingers"] = { unit = { "Blue Crag Goblin Axes", "Blue Crag Goblin Dual", "Blue Crag Goblin Spears", "Teraig Slingers" }, expRequirement = { 2, 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5, 1 }, counter = { "", "", "", "" } },

    -- turks
    ["Archer Militia"] = { unit = { "Breeland Militia", "Sworn Archers" }, expRequirement = { 2, 5 }, cost_multi = { 0.5, 1 }, counter = { "", "nd_choose_arnor" } },
    ["Breeland Militia"] = { unit = { "Archer Militia", "Sworn Spearmen" }, expRequirement = { 2, 5 }, cost_multi = { 0.5, 1 }, counter = { "", "nd_choose_arnor" } },
    ["Woodland Hunters"] = { unit = { "Lumbermen", "Sworn Archers" }, expRequirement = { 2, 7 }, cost_multi = { 0.5, 1 }, counter = { "", "nd_choose_arnor" } },
    ["Lumbermen"] = { unit = { "Woodland Hunters", "Sworn Defenders" }, expRequirement = { 2, 7 }, cost_multi = { 0.5, 1 }, counter = { "", "nd_choose_arnor" } },
    ["Watchmen Bowguard"] = { unit = { "Sworn Archers" }, expRequirement = { 0 }, cost_multi = { 0.1 }, counter = { "nd_choose_arnor" } },
    ["Dunedain Scouts"] = { unit = { "Sworn Horsemen" }, expRequirement = { 0 }, cost_multi = { 0.1 }, counter = { "nd_choose_arnor" } },
    ["Cardolan Sentinels"] = { unit = { "Sworn Archers" }, expRequirement = { 0 }, cost_multi = { 0.1 }, counter = { "nd_choose_arnor" } },
    ["Cardolan Riders"] = { unit = { "Sworn Horsemen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "nd_choose_arnor" } },
    ["Greenway Riders"] = { unit = { "Sworn Horsemen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "nd_choose_arnor" } },
    ["Greenway Spearmen"] = { unit = { "Sworn Spearmen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "nd_choose_arnor" } },
    ["Watchmen Swordguard"] = { unit = { "Sworn Defenders" }, expRequirement = { 0 }, cost_multi = { 0.1 }, counter = { "nd_choose_arnor" } },
    ["Watchmen Axeguard"] = { unit = { "Sworn Defenders" }, expRequirement = { 0 }, cost_multi = { 0.1 }, counter = { "nd_choose_arnor" } },
    ["Dunedain Volunteers"] = { unit = { "Dunedain Blademasters" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Dunedain Wardens"] = { unit = { "Dunedain Armsmen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Bandobras Archers"] = { unit = { "Watch Shirriffs", "Hobbit Infantry" }, expRequirement = { 2, 2 }, cost_multi = { 0.5, 0.5 }, counter = { "", "" } },
    ["Watch Shirriffs"] = { unit = { "Bandobras Archers", "Hobbit Infantry" }, expRequirement = { 2, 2 }, cost_multi = { 0.5, 0.5 }, counter = { "", "" } },
    ["Hobbit Infantry"] = { unit = { "Bandobras Archers", "Watch Shirriffs" }, expRequirement = { 2, 2 }, cost_multi = { 0.5, 0.5 }, counter = { "", "" } },    
    ["Dunedain Armsmen"] = { unit = { "Arthedain Knights" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "nd_choose_arnor" } },
    ["Dunedain Blademasters"] = { unit = { "Dismounted Fornost-Erain Knights" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "nd_choose_arnor" } },

    
    -- scotland
    ["Barding Marksmen"] = { unit = { "Hearthguard" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Dale Swordmasters"] = { unit = { "Dalian Paladins" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Dalian Billmen"] = { unit = { "Dalian Longbowmen", "Dalian Swordsmen", "Lake-town Pikemen" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Dalian Longbowmen"] = { unit = { "Dalian Billmen", "Dalian Swordsmen", "Barding Marksmen" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Dalian Swordsmen"] = { unit = { "Dalian Longbowmen", "Dalian Billmen", "Dale Swordmasters" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Lake-town Pikemen"] = { unit = { "Barding Hird" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Northmen Militia"] = { unit = { "Dalian Swordsmen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Rivermen"] = { unit = { "Dalian Swordsmen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Dale Cavalry"] = { unit = { "Earls" }, expRequirement = { 9 }, cost_multi = { 2 }, counter = { "" } },
    
    -- timurids
    ["Beorning Axemen"] = { unit = { "Beorning Defenders" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Beorning Defenders"] = { unit = { "Framsguard Dismounted Axemen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Beorning Spearmen"] = { unit = { "Framsguard Dismounted Spearmen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Greenwood Foresters"] = { unit = { "Greenwood Watchers" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Greenwood Watchers"] = { unit = { "Greenwood Foresters" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Vale Archers"] = { unit = { "Woodman Trackers" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Woodman Defenders"] = { unit = { "Woodman Warriors", "Woodman Hunters", "Beorning Spearmen" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Woodman Hunters"] = { unit = { "Woodman Defenders", "Woodman Warriors", "Woodman Trackers" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Woodman Warriors"] = { unit = { "Woodman Defenders", "Woodman Hunters", "Beorning Defenders" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Eotheod Horsemen"] = { unit = { "Eotheod Archers", "Eotheod Cavalry" }, expRequirement = { 7, 7 }, cost_multi = { 1, 1 }, counter = { "", "" } },
    
    -- byzantium
    ["Thorn Bladesmen"] = { unit = { "Regent Axeguard", "Thorn Guard", "Thorn Crossbowmen" }, expRequirement = { 5, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Thorn Crossbowmen"] = { unit = { "Thorn Bladesmen", "Thorn Guard", "Regent Bowguard" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Thorn Guard"] = { unit = { "Thorn Bladesmen", "Regent Spearguard", "Thorn Crossbowmen" }, expRequirement = { 2, 5, 2 }, cost_multi = { 0.5, 1, 0.5 }, counter = { "", "", "" } },
    ["Regent Spearguard"] = { unit = { "Elvellyn Vineguard" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Regent Bowguard"] = { unit = { "Elvellyn Marksmen" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Regent Axeguard"] = { unit = { "Elvellyn Infantry" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    --["Thorn Riders"] = { unit = { "Woodman Trackers" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    --["Thorn Patrolers"] = { unit = { "Woodman Trackers" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Nandor Gladeguard"] = { unit = { "Moriquendi Glademasters" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Avari Spearmen"] = { unit = { "Moriquendi Protectors" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Avari Shadows"] = { unit = { "Moriquendi Sentinels" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Nandor Glade Riders"] = { unit = { "Moriquendi Gladelords" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    
    -- teutonic_order
    ["Faolan Borderguard"] = { unit = { "Faolan Warriors", "Enedwaith Guardsmen" }, expRequirement = { 2, 5 }, cost_multi = { 0.5, 1 }, counter = { "", "" } },
    ["Faolan Warriors"] = { unit = { "Faolan Borderguard", "Clan Heralds", "Enedwaith Guardsmen" }, expRequirement = { 2, 5, 5 }, cost_multi = { 0.5, 1, 1 }, counter = { "", "", "" } },
    ["Fylani Herders"] = { unit = { "Enedwaith Cavalry" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Keefei Huntsmen"] = { unit = { "Enedwaith Marksmen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Liadan Billmen"] = { unit = { "Enedwaith Guardsmen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Liadan Spearmen"] = { unit = { "Enedwaith Guardsmen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Mochaini Touta"] = { unit = { "Mochaini Ambaxtoi" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Mordag Fishermen"] = { unit = { "Mordag Skirmishers" }, expRequirement = { 2 }, cost_multi = { 1 }, counter = { "" } },
    
    -- england
    --["Black Uruk Halberds"] = { unit = { "Morannon Gathrak" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Black Uruk Spears"] = { unit = { "Morgul Chosen" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    ["Black Uruks"] = { unit = { "Saurons Will" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    --["Morannon Gathrak"] = { unit = { "Morannon Gathrak" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Morgul Durburz"] = { unit = { "Morgul Chosen" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    ["Morannon Sharadurz"] = { unit = { "Saurons Will" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    --["Black Uruk Archers"] = { unit = { "Morgul Krushurz" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Morannon Guard"] = { unit = { "Black Uruk Spears" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Mordor Catapult"] = { unit = { "Trolls" }, expRequirement = { 2 }, cost_multi = { 0.5 }, counter = { "" } },
    ["Trolls"] = { unit = { "Mordor Catapult" }, expRequirement = { 2 }, cost_multi = { 0.5 }, counter = { "" } },
    --["Temple Knights"] = { unit = { "Melkor's Chosen" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    ["Temple Wards"] = { unit = { "Barad-dur Wardens" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    ["Orc Archers"] = { unit = { "Black Uruk Archers", "Orc Band" }, expRequirement = { 5, 2 }, cost_multi = { 1, 0.5 }, counter = { "", "" } },
    ["Orc Band"] = { unit = { "Morannon Guard", "Orc Archers" }, expRequirement = { 5, 2 }, cost_multi = { 1, 0.5 }, counter = { "", "" } },
    ["Orc Host"] = { unit = { "Black Uruks" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Orc Maulers"] = { unit = { "Mirkwood Slayers", "Black Uruk Halberds" }, expRequirement = { 5, 5 }, cost_multi = { 2, 1 }, counter = { "", "" }, faction = { "poland", "england" } },
    ["Orc Raiders"] = { unit = { "Orc Host" }, expRequirement = { 2 }, cost_multi = { 0.5 }, counter = { "" } },
    
    -- poland
    ["Dol Guldur Archers"] = { unit = { "Mirkwood Archers", "Dol Guldur Scouts", "Dol Guldur Host" }, expRequirement = { 5, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Dol Guldur Host"] = { unit = { "Dol Guldur Archers", "Dol Guldur Scouts", "Mirkwood Swords" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Dol Guldur Scouts"] = { unit = { "Dol Guldur Host", "Dol Guldur Archers" }, expRequirement = { 2, 2 }, cost_multi = { 0.5, 0.5 }, counter = { "", "" } },
    ["Mirkwood Archers"] = { unit = { "Guldur Archers" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Mirkwood Goblins"] = { unit = { "Mirkwood Hunters", "Goblin Stalkers" }, expRequirement = { 2, 5 }, cost_multi = { 0.5, 1 }, counter = { "", "" } },
    ["Mirkwood Hunters"] = { unit = { "Mirkwood Goblins", "Goblin Headhunters" }, expRequirement = { 2, 5 }, cost_multi = { 0.5, 1 }, counter = { "", "" } },
    ["Mirkwood Spears"] = { unit = { "Guldur Spears" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Mirkwood Swords"] = { unit = { "Guldur Heavy Swords" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    
    -- france
    ["Uruk Reavers"] = { unit = { "Uruk-hai Raiders","Uruk-hai Archers", "Berserkers" }, expRequirement = { 2,2, 5 }, cost_multi = { 0.5,0.5, 1 }, counter = { "","", "france" } },
    ["Uruk-hai Archers"] = { unit = { "Uruk Reavers","Uruk-hai Raiders", "Uruk-hai Crossbow" }, expRequirement = { 2,2, 5 }, cost_multi = { 0.5,0.5, 1 }, counter = { "","", "" } },
    --["Uruk-hai Crossbow"] = { unit = { "Guard of the Hand" }, expRequirement = { 9 }, cost_multi = { 3 }, counter = { "" } },
    ["Uruk-hai Raiders"] = { unit = { "Uruk Reavers","Uruk-hai Archers", "Uruk-hai Infantry" }, expRequirement = { 2,2, 5 }, cost_multi = { 0.5,0.5, 1 }, counter = { "","", "" } },
    ["Berserkers"] = { unit = { "Armoured Berserkers" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Uruk-Hai Wargriders"] = { unit = { "Champions of the White-Hand" }, expRequirement = { 9 }, cost_multi = { 2 }, counter = { "" } },

    -- aztecs
    ["Clan Axemen"] = { unit = { "Clan Spearmen", "Clan Hunters", "Warband Blades" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Clan Hunters"] = { unit = { "Warband Sentries", "Clan Spearmen", "Clan Axemen" }, expRequirement = { 5, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Clan Spearmen"] = { unit = { "Warband Host", "Clan Hunters", "Clan Axemen" }, expRequirement = { 5, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Frekkalingir Harriers"] = { unit = { "Frekkalingir Stalwarts" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Frekkalingir Hill-Riders"] = { unit = { "Frekkalingir Stalwarts" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Warband Blades"] = { unit = { "Wulfguard Axemen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Warband Host"] = { unit = { "Wulfguard Pikes" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    
    -- hre
    ["Goblin Archers"] = { unit = { "Goblin Infantry", "Goblin Band", "Black Pit Archers" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Goblin Band"] = { unit = { "Goblin Archers", "Goblin Infantry", "Black Pit Spears" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Goblin Infantry"] = { unit = { "Goblin Archers", "Goblin Band", "Black Pit Infantry" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Heavy Goblin Warg-riders"] = { unit = { "Azogs Defilers" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    ["Mountain-Orc Hunters"] = { unit = { "Mountain Uruks" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    ["Snaga Archers"] = { unit = { "Snaga Stalkers", "Snaga Skirmishers", "Goblin Archers" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Snaga Skirmishers"] = { unit = { "Snaga Stalkers", "Goblin Archers", "Snaga Archers" }, expRequirement = { 2, 5, 2 }, cost_multi = { 0.5, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Snaga Stalkers"] = { unit = { "Goblin Band", "Snaga Skirmishers", "Snaga Archers" }, expRequirement = { 5, 2, 2 }, cost_multi = { 0.5, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Warg Marauders"] = { unit = { "Mirkwood Warg-Riders", "Blackshield Warg Riders" }, expRequirement = { 5, 5 }, cost_multi = { 1, 2 }, counter = { "", "" } },
    ["Warg Riders"] = { unit = { "Heavy Goblin Warg-riders" }, expRequirement = { 5 }, cost_multi = { 2 }, counter = { "" } },
    
    -- gundabad
    ["Pale Uruks Spears"] = { unit = { "Bolgs Champions" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Blackshield Warband"] = { unit = { "Bolgs Champions" }, expRequirement = { 9 }, cost_multi = { 2 }, counter = { "" } },
    ["Blackshield Halberds"] = { unit = { "Orc Avengers" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    --["Blackshield Archers"] = { unit = { "Pale Uruks Archers" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    --["Blackshield Warriors"] = { unit = { "Pale Uruks" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Blackshield Warg Riders"] = { unit = { "Warg Avengers" }, expRequirement = { 9 }, cost_multi = { 2 }, counter = { "" } },
    ["Snow-Orc Raiders"] = { unit = { "Blackshield Warriors", "Snow-Orc Spearmen", "Snow-Orc Scouts" }, expRequirement = { 5, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Snow-Orc Scouts"] = { unit = { "Snow-Orc Raiders", "Snow-Orc Spearmen", "Blackshield Archers" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Snow-Orc Spearmen"] = { unit = { "Snow-Orc Raiders", "Blackshield Warband", "Snow-Orc Scouts" }, expRequirement = { 2, 5, 2 }, cost_multi = { 0.5, 1, 0.5 }, counter = { "", "", "" } },
        
    -- portugal
    ["Gram Armorbusters"] = { unit = { "Gram Marauders", "Gram Trackers" }, expRequirement = { 2, 2 }, cost_multi = { 0.5, 0.5 }, counter = { "", "" } },
    ["Gram Marauders"] = { unit = { "Gram Armorbusters", "Gram Trackers" }, expRequirement = { 2, 2 }, cost_multi = { 0.5, 0.5 }, counter = { "", "" } },
    ["Gram Trackers"] = { unit = { "Gram Armorbusters", "Gram Marauders" }, expRequirement = { 2, 2 }, cost_multi = { 0.5, 0.5 }, counter = { "", "" } },
    ["Angmarim Levies"] = { unit = { "Angmarim Warriors" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Hillmen"] = { unit = { "Angmarim Warriors" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Angmarim Archers"] = { unit = { "Darkblades" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Angmarim Warriors"] = { unit = { "Dreadguard" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Rhudaur Savages"] = { unit = {  "Rhudaur Huscarles" }, expRequirement = {  5 }, cost_multi = { 1 }, counter = { "" } },
    
    -- venice
    ["Loke-Innas Rim"] = { unit = { "Dragon-Wrath Kataphracts" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "balchoth_clan_joins" } },
    ["Loke-Rim Archers"] = { unit = { "Loke-Nar Rim" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Loke-Rim Cavalry"] = { unit = { "Loke-Innas Rim" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    ["Loke-Rim Pikemen"] = { unit = { "Dragons Wrath Guardians" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "balchoth_clan_joins" } },
    ["Loke-Rim Swordsmen"] = { unit = { "Dragon-Wrath Shields" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "balchoth_clan_joins" } },
    ["Rhunnic Bowmen"] = { unit = { "Loke-Rim Archers", "Rhunnic Spears", "Rhunnic Warriors" }, expRequirement = { 5, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Rhunnic Spears"] = { unit = { "Loke-Rim Spearmen", "Rhunnic Warriors", "Rhunnic Bowmen" }, expRequirement = { 5, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Rhunnic Warriors"] = { unit = { "Loke-Rim Swordsmen", "Rhunnic Spears", "Rhunnic Bowmen" }, expRequirement = { 5, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = { "", "", "" } },
    
    -- spain
    ["Haradrim Archers"] = { unit = { "Haradrim Spearmen", "Hasharii Shadows" }, expRequirement = { 2, 7}, cost_multi = {  0.5,1}, counter = {  "",""} },
    ["Haradrim Spearmen"] = { unit = { "Haradrim Archers", "Serpent Spearmen" }, expRequirement = { 2, 7 }, cost_multi = { 0.5, 1 }, counter = { "", "" } },
    ["Southron Archers"] = { unit = { "Southron Warband", "Southron Pikemen", "Hasharii Shadows" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = {  "","", "" } },
    ["Southron Pikemen"] = { unit = { "Serpent Spearmen","Southron Archers", "Southron Warband" }, expRequirement = { 5, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = {  "","", "" } },
    ["Southron Warband"] = { unit = { "Serpent Spearmen", "Southron Archers", "Southron Pikemen" }, expRequirement = { 5, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Troll-men Hunters"] = { unit = { "Troll-men Champions" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    ["Troll-men Warriors"] = { unit = { "Troll-men Champions" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    ["Southron Lancers"] = { unit = { "Serpent Guard" }, expRequirement = { 9 }, cost_multi = { 2 }, counter = { "" } },
    ["Hasharii Blades"] = { unit = { "Serpent Bladesmen" }, expRequirement = { 9 }, cost_multi = { 2 }, counter = { "" } },
    -- khand
    ["Claw-Guard"] = { unit = { "Loke-Rim Cavalry" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } }, 
    ["Marauders"] = { unit = { "Nomad Horsemen", "Khandish Raiders" }, expRequirement = { 3, 3}, cost_multi = { 0.5, 0.5 }, counter = { "", "" } },  
    ["Steppe Tribesmen"] = { unit = { "Nomad Warriors" }, expRequirement = { 3}, cost_multi = { 1 }, counter = { "" } },  
    ["Steppe Archers"] = { unit = { "Khandish Hunters" }, expRequirement = { 3}, cost_multi = { 1 }, counter = { "" } },  
    ["Khandish Raiders"] = { unit = { "Variag Horse Archers" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } }, 
    ["Nomad Axemen"] = { unit = { "Nomad Warriors", "Khandish Hunters", "Variag Swordsmen" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 1, 1 }, counter = { "", "", "" } }, 
    ["Nomad Warriors"] = { unit = { "Nomad Axemen", "Khandish Hunters", "Variag Swordsmen" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 1, 1 }, counter = { "", "", "" } }, 
    ["Khandish Hunters"] = { unit = { "Nomad Warriors", "Nomad Axemen", "Variag Bowmen" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 1, 1 }, counter = { "", "", "" } }, 

    ["Nomad Horsemen"] = { unit = { "Khand Elite Lancers" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },  
    ["Variag Swordsmen"] = { unit = { "Khand Elite Swordsmen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } }, 
    ["Variag Horse Archers"] = { unit = { "Khand Elite Horse Archers" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Khand Elite Lancers"] = { unit = { "Warlords Kataphracts" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Khand Elite Horse Archers"] = { unit = { "Warlords Kataphract Archers" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Khand Elite Swordsmen"] = { unit = { "Khand Elite Assassins" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } }, 
    --["Warlords Kataphract Archers"] = { unit = { "Khand Heavy Crossbow Chariots" }, expRequirement = { 7 }, cost_multi = { 1.5 }, counter = { "" } },
  
    -- russia
    ["Alcarondas Legion"] = { unit = { "Royal Legion of Armenelos" }, expRequirement = { 9 }, cost_multi = { 2 }, counter = { "" } },
    ["Balaketh Axeguard"] = { unit = { "Belegaer Pikemen", "Alcarondas Legion", "Belegaer Archers" }, expRequirement = { 2, 9, 2 }, cost_multi = { 0.5, 1, 0.5 }, counter = { "", "", "" } },
    ["Belegaer Archers"] = { unit = { "Belegaer Footmen", "Belegaer Pikemen", "Numenorean Marksmen" }, expRequirement = { 2, 2, 7 }, cost_multi = { 0.5, 1, 1 }, counter = { "", "", "" } },
    ["Belegaer Footmen"] = { unit = { "Numenorean Cohort", "Belegaer Pikemen", "Belegaer Archers" }, expRequirement = { 7, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Belegaer Pikemen"] = { unit = { "Numenorean Shieldguard", "Belegaer Footmen", "Belegaer Archers" }, expRequirement = { 7, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Numenorean Cohort"] = { unit = { "Alcarondas Legion" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    ["Numenorean Marksmen"] = { unit = { "Naru n'Aru Sentinels" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },
    ["Numenorean Shieldguard"] = { unit = { "Naru n'Aru Royal Guard" }, expRequirement = { 7 }, cost_multi = { 2 }, counter = { "" } },

    -- egypt

    ["Carinquar Riders"] = { unit = { "Ost-in-Edhil Rangers" }, expRequirement = { 9 }, cost_multi = { 1 }, counter = { "" } },
    ["Seregil Riders"] = { unit = { "Feanorian Lancers" }, expRequirement = { 9 }, cost_multi = { 1 }, counter = { "" } },
    ["Mornhith Warriors"] = { unit = { "Gathring Shieldbearers", "Daerbor Archers", "Dagnir Swordmasters" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5,0.5, 1 }, counter = { "","", "" } },
    ["Daerbor Archers"] = { unit = { "Gathring Shieldbearers", "Mornhith Warriors", "Doross Archers" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5,0.5, 1 }, counter = { "","", "" } },
    ["Dagnir Swordmasters"] = { unit = { "Ost-in-Edhil Champions" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Shadowblades of Himring"] = { unit = { "Ost-in-Edhil Champions" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Doross Archers"] = { unit = { "Hirneryn Marchwardens" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Feanturi Halberdiers"] = { unit = { "Sentinels of Feanor" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Gathring Shieldbearers"] = { unit = { "Daerbor Archers", "Mornhith Warriors", "Feanturi Halberdiers" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5,0.5, 1 }, counter = { "","", "" } },
    
    -- saxons
    ["Amanyar Swordmasters"] = { unit = { "Eregion Mithrim Swordsmen", "Noldorin Swords" }, expRequirement = { 0, 5 }, cost_multi = { 0.1, 1 }, counter = { "kon_council_choice_accepted", "" } },
    ["Amanyar Pikes"] = { unit = { "Eregion Amanyar Pikes", "Noldorin Defenders" }, expRequirement = { 0, 5 }, cost_multi = { 0.1, 1 }, counter = { "kon_council_choice_accepted", "" } },
    ["Amanyar Archers"] = { unit = { "Eregion Mithrim Archers", "Noldorin Archers" }, expRequirement = { 0, 5 }, cost_multi = { 0.1, 1 }, counter = { "kon_council_choice_accepted", "" } },
    ["Amanyar Riders"] = { unit = { "Eregion Mithrim Cavalry", "Amanyar Rangers" }, expRequirement = { 0, 5 }, cost_multi = { 0.1, 0.5 }, counter = { "kon_council_choice_accepted", "" } },
    ["Amanyar Rangers"] = { unit = { "Eregion Mithrim Cavalry", "Amanyar Riders" }, expRequirement = { 0, 5 }, cost_multi = { 0.1, 0.5 }, counter = { "kon_council_choice_accepted", "" } },
    ["Mounted Quendi"] = { unit = { "Eregion Mounted Quendi", "Amanyar Riders", "Amanyar Rangers" }, expRequirement = { 0, 7, 7 }, cost_multi = { 0.1, 1, 1 }, counter = { "kon_council_choice_accepted", "", ""  } },
    ["Bow Quendi"] = { unit = { "Spear Quendi", "Sword Quendi", "Amanyar Archers" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Spear Quendi"] = { unit = { "Bow Quendi", "Spear Quendi", "Amanyar Pikes" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Sword Quendi"] = { unit = { "Bow Quendi", "Spear Quendi", "Amanyar Swordmasters" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    
    -- ireland
    ["Lorien Archers"] = { unit = { "Lothlorien Marchwardens", "Lorien Warders", "Lorien Sentries" }, expRequirement = { 5, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Lothlorien Marchwardens"] = { unit = { "Galadhrim Archers" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },


    ["Ent Catapult"] = { unit = { "Ents" }, expRequirement = { 2 }, cost_multi = { 0.5 }, counter = { "" } },
    ["Ents"] = { unit = { "Ent Catapult" }, expRequirement = { 2 }, cost_multi = { 0.5 }, counter = { "" } },
    ["Gurdhinen"] = { unit = { "Galadhrim Swordsmen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Hitherbin"] = { unit = { "Galadhrim Cavalry" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Lorien Scouts"] = { unit = { "Hitherbin" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Lorien Sentries"] = { unit = { "Sentinels of Cerin Amroth", "Lorien Warders", "Lorien Archers" }, expRequirement = { 5, 2, 2 }, cost_multi = { 1, 0.5, 0.5 }, counter = { "", "", "" } },
    ["Lorien Warders"] = { unit = { "Lorien Sentries", "Lorien Archers", "Sentinels of Cerin Amroth" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Sentinels of Cerin Amroth"] = { unit = { "Galadhrim Swordsmen" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    
    -- mongols
    ["Elder Council"] = { unit = { "Elvenking's Palace Guard" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Elven Bow Stagriders"] = { unit = { "Heavy Spear Stagriders" }, expRequirement = { 9 }, cost_multi = { 1 }, counter = { "" } },
    ["Maethyr i-Thewair"] = { unit = { "Elvenkings Axeguard" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Woodland Scouts"] = { unit = { "Woodland Spearmen", "Woodland Wardens", "Woodland Warriors", "Woodland Sentinels" }, expRequirement = { 2, 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5, 1 }, counter = { "", "", "", "" } },
    ["Woodland Sentinels"] = { unit = { "Elvenkings Bowguard" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Woodland Spearmen"] = { unit = { "Woodland Scouts", "Woodland Warriors", "Woodland Wardens", "Maethyr i-Thewair" }, expRequirement = { 2, 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5, 2 }, counter = { "", "", "", "" } },
    ["Woodland Wardens"] = { unit = { "Woodland Scouts", "Woodland Spearmen", "Woodland Warriors", "Elder Council" }, expRequirement = { 2, 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5, 2 }, counter = { "", "", "", "" } },
    ["Woodland Warriors"] = { unit = { "Woodland Scouts", "Woodland Spearmen", "Woodland Wardens", "Maethyr i-Thewair" }, expRequirement = { 2, 2, 2, 5 }, cost_multi = { 0.5, 0.5, 0.5, 1 }, counter = { "", "", "", "" } },
        
    -- denmark
    ["Lindar Bowmen"] = { unit = { "Sindar Archers", "Lindon Longspears", "Lindar Mariners", "Lindar Guards" }, expRequirement = { 5, 2, 2, 2 }, cost_multi = { 1, 0.5, 0.5, 0.5 }, counter = { "", "", "", "" } },
    ["Lindar Guards"] = { unit = { "Sindar Axemen","Lindar Mariners", "Lindar Bowmen", "Lindon Longspears" }, expRequirement = { 5, 2, 2, 2 }, cost_multi = { 1, 0.5, 0.5, 0.5 }, counter = { "", "", "", "" } },
    ["Lindar Mariners"] = { unit = { "Heavy Falathrim Shipwrights", "Lindar Bowmen", "Lindon Longspears", "Lindar Guards" }, expRequirement = { 5, 2, 2, 2 }, cost_multi = { 1, 0.5, 0.5, 0.5 }, counter = { "", "", "", "" } },
    ["Lindon Longspears"] = { unit = { "Sindar Spearmen", "Lindar Mariners", "Lindar Bowmen", "Lindar Guards" }, expRequirement = { 5, 2, 2, 2 }, cost_multi = { 1, 0.5, 0.5, 0.5 }, counter = { "", "", "", "" } },
    ["Sindar Spearmen"] = { unit = { "Eregion Mithrim Spearmen", "Heavy Falathrim Spears" }, expRequirement = { 0, 5 }, cost_multi = { 0.1, 1 }, counter = { "kon_council_choice_accepted", "" } },
    ["Sindar Axemen"] = { unit = { "Eregion Mithrim Swordsmen", "Heavy Falathrim Wavebreakers" }, expRequirement = { 0, 5 }, cost_multi = { 0.1, 1 }, counter = { "kon_council_choice_accepted", "" } },
    ["Sindar Archers"] = { unit = { "Eregion Mithrim Archers", "Heavy Falathrim Archers" }, expRequirement = { 0, 5 }, cost_multi = { 0.1, 1 }, counter = { "kon_council_choice_accepted", "" } },
    ["Sindar Riders"] = { unit = { "Eregion Mithrim Cavalry", "Heavy Falathrim Skirmishers" }, expRequirement = { 0, 7 }, cost_multi = { 0.1, 1 }, counter = { "kon_council_choice_accepted", "" } },
      
    -- KoN
    ["Noldorin Swords"] = { unit = { "Noldorin Cundo Swords" }, expRequirement = { 0 }, cost_multi = { 0.1 }, counter = { "kon_council_choice_accepted" } },
    ["Noldorin Defenders"] = { unit = { "Noldorin Cundo Pikes" }, expRequirement = { 0 }, cost_multi = { 0.1 }, counter = { "kon_council_choice_accepted" } },
    ["Noldorin Veterans"] = { unit = { "Noldorin Cundo Halberds" }, expRequirement = { 0 }, cost_multi = { 0.1 }, counter = { "kon_council_choice_accepted" } },
    ["Noldorin Archers"] = { unit = { "Noldorin Cundo Bows" }, expRequirement = { 0 }, cost_multi = { 0.1 }, counter = { "kon_council_choice_accepted" } },
    ["Heavy Falathrim Axeguard"] = { unit = { "Eregion Barad Axeguard" }, expRequirement = { 0 }, cost_multi = { 0.1 }, counter = { "kon_council_choice_accepted" } },
    ["Heavy Falathrim Shipwrights"] = { unit = { "Eregion Barad Marines" }, expRequirement = { 0 }, cost_multi = { 0.1 }, counter = { "kon_council_choice_accepted" } },
    ["Heavy Falathrim Archers"] = { unit = { "Eregion Barad Archers" }, expRequirement = { 0 }, cost_multi = { 0.1 }, counter = { "kon_council_choice_accepted" } },
    ["Heavy Falathrim Skirmishers"] = { unit = { "Eregion Barad Skirmishers" }, expRequirement = { 0 }, cost_multi = { 0.1 }, counter = { "kon_council_choice_accepted" } },
    ["Eregion Spear Quendi"] = { unit = { "Eregion Sword Quendi", "Eregion Bow Quendi", "Eregion Mithrim Spearmen" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Eregion Sword Quendi"] = { unit = { "Eregion Spear Quendi", "Eregion Bow Quendi", "Eregion Mithrim Swordsmen" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Eregion Bow Quendi"] = { unit = { "Eregion Spear Quendi", "Eregion Sword Quendi", "Eregion Mithrim Archers" }, expRequirement = { 2, 2, 5 }, cost_multi = { 0.5, 0.5, 1 }, counter = { "", "", "" } },
    ["Eregion Mithrim Spearmen"] = { unit = { "Eregion Barad Spearmen" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Eregion Mithrim Swordsmen"] = { unit = { "Eregion Barad Bladesmen" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Eregion Mithrim Archers"] = { unit = { "Eregion Barad Archers" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Eregion Mithrim Cavalry"] = { unit = { "Eregion Barad Riders" }, expRequirement = { 7 }, cost_multi = { 1 }, counter = { "" } },
    ["Eregion Mounted Quendi"] = { unit = { "Eregion Mithrim Cavalry" }, expRequirement = { 5 }, cost_multi = { 1 }, counter = { "" } },
    ["Eregion Lindar Bowmen"] = { unit = { "Eregion Mithrim Archers", "Eregion Lindon Longspears", "Eregion Lindar Mariners", "Eregion Lindar Guards" }, expRequirement = { 5, 2, 2, 2 }, cost_multi = { 1, 0.5, 0.5, 0.5 }, counter = { "", "", "", "" } },
    ["Eregion Lindar Guards"] = { unit = { "Eregion Mithrim Swordsmen", "Eregion Lindar Mariners", "Eregion Lindar Bowmen", "Eregion Lindon Longspears" }, expRequirement = { 5, 2, 2, 2 }, cost_multi = { 1, 0.5, 0.5, 0.5 }, counter = { "", "", "", "" } },
    ["Eregion Lindar Mariners"] = { unit = { "Eregion Mithrim Swordsmen", "Eregion Lindar Bowmen", "Eregion Lindon Longspears", "Eregion Lindar Guards" }, expRequirement = { 5, 2, 2, 2 }, cost_multi = { 1, 0.5, 0.5, 0.5 }, counter = { "", "", "", "" } },
    ["Eregion Lindon Longspears"] = { unit = { "Eregion Mithrim Spearmen", "Eregion Lindar Mariners", "Eregion Lindar Bowmen", "Eregion Lindar Guards" }, expRequirement = { 5, 2, 2, 2 }, cost_multi = { 1, 0.5, 0.5, 0.5 }, counter = { "", "", "", "" } },
    }